version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "/sdk/python"
      - "/sdk/python-langchain"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
