"""Python client SDK for the Taguru long-term semantic memory server.

Quick start::

    from taguru import Taguru

    client = Taguru()  # TAGURU_URL / TAGURU_API_TOKEN, else localhost:8248
    ctx = client.context("sake")
    hits = ctx.search_passages("酒蔵の創業年", limit=5)

``AsyncTaguru`` is the identical async surface. The behavioral contract is
the server's own protocol document: ``client.protocol()`` (GET /protocol).
"""

from __future__ import annotations

from ._async.client import AsyncContext, AsyncContexts, AsyncGroups, AsyncTaguru
from ._contract import SUPPORTED_HTTP_CONTRACTS
from ._errors import (
    AuthenticationError,
    ConflictError,
    EmbeddingUnavailableError,
    IncompatibleServerError,
    NotFoundError,
    PayloadTooLargeError,
    PermissionDeniedError,
    RateLimitError,
    RequestTimeoutError,
    ResponseShapeError,
    ServerError,
    ServiceUnavailableError,
    StorageFullError,
    TaguruError,
    TransportError,
    UnexpectedStatusError,
    ValidationError,
    error_for_status,
)
from ._models import (
    Activation,
    ActivationPage,
    AliasEntry,
    AliasPage,
    Association,
    Attribution,
    BatchApplyResult,
    Bm25Explain,
    BudgetLimits,
    BudgetUsage,
    Citation,
    CitationEntry,
    CitationRef,
    CommunityHit,
    CommunityHitMember,
    CommunityPage,
    CommunityRevisions,
    CompactOutcome,
    ConceptDescription,
    ContextMeta,
    ContextPage,
    ContextRevision,
    ContextStats,
    ContextUsage,
    Corroboration,
    CrossAssociation,
    CrossMatchPage,
    CrossPassageHit,
    CrossPassagePage,
    DirectoryEntry,
    DriftAudit,
    EvidenceItem,
    EvidenceLanesPlan,
    EvidencePackage,
    EvidencePlan,
    ExplorePage,
    FilterPlan,
    GroupEntry,
    GroupImportOutcome,
    GroupPage,
    ImportOutcome,
    ImportResult,
    LabelPage,
    LabelUsage,
    LaneEvidence,
    LanePlan,
    LaneRank,
    LexicalExplain,
    Locator,
    MatchPage,
    MatchPlan,
    NearestGloss,
    NearestResolution,
    NearestSpellings,
    OmittedCandidate,
    PassageHit,
    PassageLanes,
    PassageLookup,
    PassagePage,
    RankingExplain,
    Recollection,
    RefreshBreakdown,
    RefreshOutcome,
    RerankerPlan,
    ResolveExplanation,
    ResolveRanking,
    RetractAssociationOutcome,
    RetractOutcome,
    RetrievalResult,
    SearchContextPlan,
    SearchExplanation,
    SearchLanesPlan,
    SearchPlan,
    SelectionPlan,
    SemanticExplain,
    SourceEntry,
    SourcePage,
    StoredPassages,
    TermContribution,
    TieredResolution,
    TwinPair,
    UnsourcedEdge,
    VectorExplain,
    VocabularyAudit,
)
from ._shared import citation_key
from ._sync.client import Context, Contexts, Groups, Taguru
from ._types import (
    AssocOp,
    BudgetRequest,
    CrossMatchCursor,
    ExploreCursor,
    LocatorInput,
    LocatorSpec,
    MatchCursor,
    QuestionSpec,
    RerankRequest,
    SectionSpec,
)

__version__ = "0.6.0"

__all__ = [
    "__version__",
    # clients
    "Taguru",
    "AsyncTaguru",
    "Context",
    "AsyncContext",
    "Contexts",
    "AsyncContexts",
    "Groups",
    "AsyncGroups",
    "citation_key",
    # request types
    "AssocOp",
    "QuestionSpec",
    "SectionSpec",
    "LocatorInput",
    "LocatorSpec",
    "MatchCursor",
    "CrossMatchCursor",
    "ExploreCursor",
    "BudgetRequest",
    "RerankRequest",
    # wire-contract compatibility (ADR 0005 §3.8)
    "SUPPORTED_HTTP_CONTRACTS",
    # errors
    "TaguruError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "ConflictError",
    "ValidationError",
    "PayloadTooLargeError",
    "RequestTimeoutError",
    "RateLimitError",
    "ServerError",
    "ServiceUnavailableError",
    "StorageFullError",
    "EmbeddingUnavailableError",
    "TransportError",
    "UnexpectedStatusError",
    "IncompatibleServerError",
    "ResponseShapeError",
    "error_for_status",
    # models
    "Activation",
    "ActivationPage",
    "AliasEntry",
    "AliasPage",
    "Association",
    "Attribution",
    "BatchApplyResult",
    "Bm25Explain",
    "BudgetLimits",
    "BudgetUsage",
    "Citation",
    "CitationEntry",
    "CitationRef",
    "CommunityHit",
    "CommunityHitMember",
    "CommunityPage",
    "CommunityRevisions",
    "CompactOutcome",
    "ConceptDescription",
    "ContextMeta",
    "ContextRevision",
    "ContextPage",
    "ContextStats",
    "ContextUsage",
    "Corroboration",
    "CrossAssociation",
    "CrossMatchPage",
    "CrossPassageHit",
    "CrossPassagePage",
    "DirectoryEntry",
    "DriftAudit",
    "EvidenceItem",
    "EvidenceLanesPlan",
    "EvidencePackage",
    "EvidencePlan",
    "ExplorePage",
    "FilterPlan",
    "GroupEntry",
    "GroupImportOutcome",
    "GroupPage",
    "ImportOutcome",
    "ImportResult",
    "LabelPage",
    "LabelUsage",
    "LaneEvidence",
    "LanePlan",
    "LaneRank",
    "LexicalExplain",
    "Locator",
    "MatchPage",
    "MatchPlan",
    "NearestGloss",
    "NearestResolution",
    "NearestSpellings",
    "OmittedCandidate",
    "PassageHit",
    "PassageLanes",
    "PassageLookup",
    "PassagePage",
    "RankingExplain",
    "Recollection",
    "RefreshBreakdown",
    "RefreshOutcome",
    "RerankerPlan",
    "ResolveExplanation",
    "ResolveRanking",
    "RetractAssociationOutcome",
    "RetractOutcome",
    "RetrievalResult",
    "SearchContextPlan",
    "SearchExplanation",
    "SearchLanesPlan",
    "SearchPlan",
    "SelectionPlan",
    "SemanticExplain",
    "SourceEntry",
    "SourcePage",
    "StoredPassages",
    "TermContribution",
    "TieredResolution",
    "TwinPair",
    "UnsourcedEdge",
    "VectorExplain",
    "VocabularyAudit",
]
