"""LangChain integration for the Taguru long-term semantic memory server.

Three entry points:

- :class:`TaguruRetriever` — the documented retrieval loop (graph lane +
  text lane, RRF-merged) as a LangChain ``BaseRetriever``.
- :class:`TaguruIngester` — the LangChain twin of ``taguru extract``: a chat
  model decomposes Documents into associations under the protocol's ingest
  discipline, applied via ``POST /import`` (per-source replace, idempotent).
- :mod:`taguru_langchain.ingest_connectors` (ADR 0007, issue #347) — the
  normalized document contract standard ingest connectors (``.md``/``.txt``/
  ``.pdf``/``.html``/``.docx``/``.pptx``/S3) produce, and the bridge that
  feeds a
  :class:`~taguru_langchain.ingest_connectors.document.ConnectorDocument`
  into :class:`TaguruIngester` instead of a bare string.

Deliberately NOT provided: a VectorStore facade (Taguru's retrieval is
structural-first; forcing it behind ``similarity_search`` would misrepresent
resolve/activate semantics), a Memory class (deprecated upstream in favor of
LangGraph state), and agent Tools (the MCP bridge ``taguru-mcp`` already
serves the identical tool vocabulary — pair it with ``langchain-mcp-adapters``).
"""

from __future__ import annotations

from ._extract import MODEL_OUTPUT_JSON_SCHEMA
from .checkpoints import CheckpointStore, FilesystemCheckpointStore
from .events import (
    AttemptFailed,
    AttemptStarted,
    ChunkCompleted,
    ChunkStarted,
    DocumentStarted,
    EmbeddingRefreshCompleted,
    EmbeddingRefreshStarted,
    EmbeddingRefreshWarning,
    ImportCompleted,
    ImportStarted,
    IngestEvent,
    IngestEventCallback,
    ProviderMetadata,
)
from .ingest import IngestOutcome, TaguruIngester
from .ingest_connectors import (
    CONNECTOR_DOCUMENT_VERSION,
    DIAGNOSTIC_CODES,
    PHASES,
    RUN_SUMMARY_VERSION,
    AzureBlobObjectStore,
    Connector,
    ConnectorCheckpoint,
    ConnectorDocument,
    ConnectorMetadata,
    DeletionPolicy,
    Diagnostic,
    DiagnosticCode,
    DocxConnector,
    FetchedObject,
    FileObjectStore,
    FileProbe,
    FileProbeCheckpoint,
    FingerprintInputs,
    FingerprintTier,
    GCSObjectStore,
    HtmlConnector,
    LocatorEntry,
    ObjectMeta,
    ObjectNotFoundError,
    ObjectStore,
    OcrAdapter,
    OcrRecoveredUnit,
    OcrRequest,
    OcrResult,
    PdfConnector,
    PermanentStoreError,
    Phase,
    PptxConnector,
    ReferenceKind,
    ReferencePlan,
    RunRecorder,
    RunReport,
    S3Connector,
    S3ObjectCheckpoint,
    S3ObjectStore,
    S3SyncReport,
    SectionEntry,
    SourceEvent,
    SourceEventSink,
    SourceIdRegistry,
    TextFileConnector,
    TransientStoreError,
    aingest_connector_document,
    aingest_connector_documents,
    canonicalize_url,
    check_source_id,
    default_connectors,
    file_source_id,
    ingest_connector_document,
    ingest_connector_documents,
    object_fingerprint,
    open_object_store,
    options_digest,
    plan_references,
    sub_source_id,
    sync_object_storage,
    sync_references,
    watch_directory,
)
from .retrievers import TaguruRetriever

__version__ = "0.9.5"

__all__ = [
    "TaguruRetriever",
    "TaguruIngester",
    "IngestOutcome",
    "MODEL_OUTPUT_JSON_SCHEMA",
    "CheckpointStore",
    "FilesystemCheckpointStore",
    "IngestEvent",
    "IngestEventCallback",
    "ProviderMetadata",
    "DocumentStarted",
    "ChunkStarted",
    "AttemptStarted",
    "AttemptFailed",
    "ChunkCompleted",
    "ImportStarted",
    "ImportCompleted",
    "EmbeddingRefreshStarted",
    "EmbeddingRefreshCompleted",
    "EmbeddingRefreshWarning",
    "CONNECTOR_DOCUMENT_VERSION",
    "DIAGNOSTIC_CODES",
    "PHASES",
    "RUN_SUMMARY_VERSION",
    "Connector",
    "ConnectorCheckpoint",
    "AzureBlobObjectStore",
    "ConnectorDocument",
    "ConnectorMetadata",
    "DeletionPolicy",
    "Diagnostic",
    "DiagnosticCode",
    "DocxConnector",
    "FetchedObject",
    "FileObjectStore",
    "FileProbe",
    "FileProbeCheckpoint",
    "FingerprintInputs",
    "FingerprintTier",
    "GCSObjectStore",
    "HtmlConnector",
    "LocatorEntry",
    "ObjectMeta",
    "ObjectNotFoundError",
    "ObjectStore",
    "OcrAdapter",
    "OcrRecoveredUnit",
    "OcrRequest",
    "OcrResult",
    "PdfConnector",
    "PermanentStoreError",
    "Phase",
    "PptxConnector",
    "ReferenceKind",
    "ReferencePlan",
    "RunRecorder",
    "RunReport",
    "S3Connector",
    "S3ObjectCheckpoint",
    "S3ObjectStore",
    "S3SyncReport",
    "SectionEntry",
    "SourceEvent",
    "SourceEventSink",
    "SourceIdRegistry",
    "TextFileConnector",
    "TransientStoreError",
    "aingest_connector_document",
    "aingest_connector_documents",
    "canonicalize_url",
    "check_source_id",
    "default_connectors",
    "file_source_id",
    "ingest_connector_document",
    "ingest_connector_documents",
    "object_fingerprint",
    "open_object_store",
    "options_digest",
    "plan_references",
    "sub_source_id",
    "sync_object_storage",
    "sync_references",
    "watch_directory",
    "__version__",
]
