/**
 * TypeScript/JavaScript client SDK for the Taguru long-term semantic memory
 * server.
 *
 * Quick start:
 * ```ts
 * import { Taguru } from "taguru";
 *
 * const client = new Taguru(); // TAGURU_URL / TAGURU_API_TOKEN, else localhost:8248
 * const ctx = client.context("sake");
 * const hits = await ctx.searchPassages("酒蔵の創業年", { limit: 5 });
 * ```
 *
 * The behavioral contract is the server's own protocol document:
 * `await client.protocol()` (GET /protocol).
 */

export { Taguru, Contexts, Groups, Context, type TaguruOptions } from "./client.js";
export {
  TaguruError,
  type TaguruErrorOptions,
  AuthenticationError,
  PermissionDeniedError,
  NotFoundError,
  ConflictError,
  ValidationError,
  PayloadTooLargeError,
  RequestTimeoutError,
  RateLimitError,
  ServerError,
  ServiceUnavailableError,
  StorageFullError,
  EmbeddingUnavailableError,
  TransportError,
  UnexpectedStatusError,
  IncompatibleServerError,
  errorForStatus,
} from "./errors.js";
// Wire-contract compatibility (ADR 0005 §3.8).
export { SUPPORTED_HTTP_CONTRACTS } from "./contract.js";
export { VERSION } from "./version.js";
export {
  citationKey,
  type Activation,
  type ActivationPage,
  type AddAssociationsResult,
  type AliasEntry,
  type AliasPage,
  type AssocOp,
  type Association,
  type Attribution,
  type AuditAliases,
  type AuditNames,
  type BatchApplyResult,
  type Bm25Explain,
  type BudgetLimits,
  type BudgetRequest,
  type BudgetUsage,
  type Citation,
  type CitationEntry,
  type CitationRef,
  type CommunityHit,
  type CommunityHitMember,
  type CommunityPage,
  type CommunityRevisions,
  type CompactOutcome,
  type ConceptDescription,
  type ContextMeta,
  type ContextRevision,
  type ContextPage,
  type ContextStats,
  type ContextUsage,
  type Corroboration,
  type CrossAssociation,
  type CrossMatchCursor,
  type CrossMatchPage,
  type CrossPassageHit,
  type CrossPassagePage,
  type DirectoryEntry,
  type DriftAudit,
  type EvidenceItem,
  type EvidenceLanesPlan,
  type EvidencePackage,
  type EvidencePlan,
  type ExploreCursor,
  type ExplorePage,
  type FilterPlan,
  type GroupEntry,
  type GroupImportOutcome,
  type GroupPage,
  type ImportOutcome,
  type ImportResult,
  type Issue,
  type LabelPage,
  type LabelUsage,
  type LaneEvidence,
  type LanePlan,
  type LaneRank,
  type LexicalExplain,
  type MatchCursor,
  type MatchPage,
  type MatchPlan,
  type NearestGloss,
  type NearestResolution,
  type NearestSpellings,
  type OmittedCandidate,
  type OneOrMany,
  type Open,
  type PassageHit,
  type PassageLanes,
  type PassageLookup,
  type PassagePage,
  type PathsPage,
  type QuestionSpec,
  type RankingExplain,
  type Recollection,
  type RefreshBreakdown,
  type RefreshOutcome,
  type RelationDef,
  type RerankerPlan,
  type RerankRequest,
  type ResolveExplanation,
  type ResolveRanking,
  type RetractAssociationOutcome,
  type RetractOutcome,
  type RetrievalResult,
  type SchemaAudit,
  type SchemaDocument,
  type SchemaImportOutcome,
  type SchemaViolation,
  type SearchContextPlan,
  type SearchExplanation,
  type SearchLanesPlan,
  type SearchPlan,
  type SectionSpec,
  type SelectionPlan,
  type SemanticExplain,
  type SourceEntry,
  type SourcePage,
  type StoredPassages,
  type TermContribution,
  type TieredResolution,
  type Trail,
  type TwinPair,
  type TypeDef,
  type UnsourcedEdge,
  type VectorExplain,
  type VocabularyAudit,
} from "./models.js";
